/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.GUI;

import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import poker.domain.Card;
import poker.logic.Calculate;
import poker.logic.WinningHands;

/**
 *
 * @author Ivan Local
 */
public class PokerUsingJFrameForm extends javax.swing.JFrame {

    /**
     * Creates new form PokerUsingJFrameForm
     */
    public PokerUsingJFrameForm() {
        initComponents();
        this.isFirstHand = true;
        this.cards = new ArrayList<>();
        this.cardIcons = new ArrayList<>();
        this.heldCards = new ArrayList<>();
        cards.add(buttonCard1);
        cards.add(buttonCard2);
        cards.add(buttonCard3);
        cards.add(buttonCard4);
        cards.add(buttonCard5);
        this.calculate = new Calculate(100, 5);
        for (int i = 0; i < 5; i++) {
            heldCards.add(false);
        }
        System.out.println("Is this First Hand " + this.isFirstHand);
        System.out.println("To be replaced " + this.heldCards);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBifePoker = new javax.swing.JLabel();
        labelBalance = new javax.swing.JLabel();
        buttonDeal = new javax.swing.JButton();
        buttonCard3 = new javax.swing.JButton();
        buttonCard1 = new javax.swing.JButton();
        buttonCard4 = new javax.swing.JButton();
        buttonCard5 = new javax.swing.JButton();
        buttonCard2 = new javax.swing.JButton();
        labelBalanceAmount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        betAmount = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBifePoker.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelBifePoker.setText("Bife Poker");

        labelBalance.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelBalance.setText("Credit");

        buttonDeal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buttonDeal.setText("DEAL");
        buttonDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDealActionPerformed(evt);
            }
        });

        buttonCard3.setText("jButton3");
        buttonCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCard3ActionPerformed(evt);
            }
        });

        buttonCard1.setText("jButton3");
        buttonCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCard1ActionPerformed(evt);
            }
        });

        buttonCard4.setText("jButton3");
        buttonCard4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCard4ActionPerformed(evt);
            }
        });

        buttonCard5.setText("jButton3");
        buttonCard5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCard5ActionPerformed(evt);
            }
        });

        buttonCard2.setText("jButton3");
        buttonCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCard2ActionPerformed(evt);
            }
        });

        labelBalanceAmount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelBalanceAmount.setText("balance");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Bet");

        betAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        betAmount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "20", "50", "100", "200", "500", "1000" }));
        betAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betAmount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeal, javax.swing.GroupLayout.PREFERRED_SIZE, 1683, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(838, 838, 838)
                                .addComponent(labelBifePoker, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelBalance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelBalanceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(buttonCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBifePoker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelBalance)
                    .addComponent(labelBalanceAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonDeal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(betAmount, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDealActionPerformed
        // TODO add your handling code here:
        System.out.println("***********************");
        System.out.println("Button DEAL is clicked");
        //System.out.println("Is first hand " + isFirstHand);
        //System.out.println("Cards to be replaced " + this.heldCards);
        if (this.isFirstHand == true) {
            System.out.println("This is first hand");
            this.calculate.makeFirstHand();
            drawCards();
            this.isFirstHand = false;
            System.out.println("After beeing true now isFirstHand " + this.isFirstHand);

        } else {
            System.out.println("This is second hand");
            String cardsSelectedString = this.stringCardsSelected();
            System.out.println("String input for postions to be replaced are " + cardsSelectedString);
            this.calculate.replaceCards(cardsSelectedString);
            drawReplacedCards();
            WinningHands wh = new WinningHands(this.calculate.getDeal().getHand(), this.calculate.getBet());
            this.calculate.addToBalance(wh.calculateWinningHand());
            System.out.println("Balnce after hand is " + calculate.getBalance());
            this.labelBalanceAmount.setText(String.valueOf(calculate.getBalance()));
            this.isFirstHand = true;
            this.cardIcons.clear();
            for (boolean bool : this.heldCards) {
                bool = false;
            }
                
        }

    }//GEN-LAST:event_buttonDealActionPerformed

    private void betAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betAmountActionPerformed
        // TODO add your handling code here:
        String value = (String) betAmount.getSelectedItem();
        int bet = Integer.valueOf(value);
        calculate.setBet(bet);
    }//GEN-LAST:event_betAmountActionPerformed

    private void buttonCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCard1ActionPerformed
        // TODO add your handling code here:
        if (this.isFirstHand = true) {
            int i = 0;
            helpButtonCardSelected(i);
        }
    }//GEN-LAST:event_buttonCard1ActionPerformed

    private void buttonCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCard2ActionPerformed
        // TODO add your handling code here
        if (this.isFirstHand = true) {
            int i = 1;
            helpButtonCardSelected(i);
        }
    }//GEN-LAST:event_buttonCard2ActionPerformed

    private void buttonCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCard3ActionPerformed
        // TODO add your handling code here:
        if (this.isFirstHand = true) {
            int i = 2;
            helpButtonCardSelected(i);
        }
    }//GEN-LAST:event_buttonCard3ActionPerformed

    private void buttonCard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCard4ActionPerformed
        // TODO add your handling code here:
        if (this.isFirstHand = true) {
            int i = 3;
            helpButtonCardSelected(i);
        }
    }//GEN-LAST:event_buttonCard4ActionPerformed

    private void buttonCard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCard5ActionPerformed
        // TODO add your handling code here:
        if (this.isFirstHand = true) {
            int i = 4;
            helpButtonCardSelected(i);
        }
    }//GEN-LAST:event_buttonCard5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokerUsingJFrameForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokerUsingJFrameForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokerUsingJFrameForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokerUsingJFrameForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokerUsingJFrameForm().setVisible(true);
            }
        });
    }

    //moje metode
    private Icon getCardImage(String locationURL) {
        try {
            File file = new File(locationURL);
            BufferedImage originalImage = ImageIO.read(file);
            int height = originalImage.getHeight();
            int width = originalImage.getWidth();
            //System.out.println("Original image size is height " + height + " width is " + width);
            Icon card = new ImageIcon(locationURL);
            return card;
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
        return null;
    }

    //helper metoda buttonima za karte da se vidi da li su obelezeni ili nisu
    private void helpButtonCardSelected(int i) {
        if (this.heldCards.get(i) == true) {
            this.heldCards.set(i, false);
            cards.get(i).setIcon(getCardImage("Pictures/yellow_back.png"));
            System.out.println("Card " + i + " will be replaced");
        } else {
            this.heldCards.set(i, true);
            cards.get(i).setIcon(this.cardIcons.get(i));
            System.out.println("Card " + i + " will be held");
        }
    }

    //helper za odredjivanje stringa karata to be replaced
    private String stringCardsSelected() {
        StringBuilder sb = new StringBuilder();
        if (this.heldCards.get(0) == false) {
            sb.append('q');
        }
        if (this.heldCards.get(1) == false) {
            sb.append('w');
        }
        if (this.heldCards.get(2) == false) {
            sb.append('e');
        }
        if (this.heldCards.get(3) == false) {
            sb.append('r');
        }
        if (this.heldCards.get(4) == false) {
            sb.append('t');
        }
        return sb.toString();
    }

    private void drawCards() {
        this.labelBalanceAmount.setText(String.valueOf(calculate.getBalance()));
        for (Card card : calculate.getDeal().getHand().getPlayerHand()) {
            this.cardIcons.add(getCardImage(card.getImageLocation()));
        }

        for (int i = 0; i < cards.size(); i++) {
            cards.get(i).setIcon(this.cardIcons.get(i));
        }
    }

    private void drawReplacedCards() {
        int i;
        this.cardIcons.clear();
        for (i = 0; i < 5; i++) {
            Card card = this.calculate.getDeal().getHand().getPlayerHand().get(i);
            this.cardIcons.add(getCardImage(card.getImageLocation()));
            cards.get(i).setIcon(this.cardIcons.get(i));
        }
    }

    private ArrayList<Icon> cardIcons;
    private ArrayList<Boolean> heldCards;
    private boolean isFirstHand;
    private ArrayList<JButton> cards;
    private Calculate calculate;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> betAmount;
    private javax.swing.JButton buttonCard1;
    private javax.swing.JButton buttonCard2;
    private javax.swing.JButton buttonCard3;
    private javax.swing.JButton buttonCard4;
    private javax.swing.JButton buttonCard5;
    private javax.swing.JButton buttonDeal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBalance;
    private javax.swing.JLabel labelBalanceAmount;
    private javax.swing.JLabel labelBifePoker;
    // End of variables declaration//GEN-END:variables
}
